- name: Update all packages to their latest version
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: apt dist-upgrade
  apt:
    upgrade: dist
    notify: apt cleanup
