- name: Update all packages to their latest version
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required and purge their configuration files
  apt:
    autoremove: yes
    purge: true
