targets:
  hosts:
    localhost:
      ansible_connection: local
      docker:
        docker_registry: https://docker.arvancloud.ir
      ubuntu:
        codeName: noble
      ansible_password: "@Hoo3ein_Rad"