# - name: Full server provisioning
- hosts: targets
  become: true
  # roles:
  #   - base
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes